language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: trusty
    - php: 7.0
      dist: trusty
    - php: hhvm
      dist: trusty

before_script: 
  - composer install --dev
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
script: cd tests && php all_tests.php && cd ..
